[package]
name = "letuspray"
version = "0.1.0"
edition = "2021"

[dependencies]
pray_engine = { path = "../parser" }
tera = "1"
notify = "6.1.1"
glob = "0.3.1"

[[bin]]
name = 'pray'
path = 'src/main.rs'
