[package]
name = "letuspray"
version = "0.1.0"
edition = "2021"

[dependencies]
pray_engine = { path = "../parser" }
tera = "1"
serde = "1.0"
serde_yml = "0.0.12"

[[bin]]
name = 'pray'
path = 'src/main.rs'