[package]
name = "letuspray"  # Replace with your project's name
version = "0.1.0"           # The current version of your project

[dependencies]
pray_engine = { path = "../parser" }
tuirealm = "^1.9.0"

[[bin]]
name = 'pray'
path = 'src/main.rs'